name: PALMHR_MOBILE
description: "HR Management app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  action_slider: ^0.7.0
  auto_route: ^7.9.2
  auto_route_generator: ^7.3.2
  babstrap_settings_screen: ^0.1.6
  clay_containers: ^0.3.4
  fl_chart: ^0.66.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  wolt_modal_sheet: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
