name: apex_time_sync_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  getwidget: ^2.0.4
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  babstrap_settings_screen: ^0.1.6
  fl_chart: ^0.66.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  wolt_modal_sheet: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
